import { Opportunity } from "@/types";
import { CAPITAL_REGION_TAG } from "./constants";

/**
 * DEMO / DEVELOPMENT DATA ONLY.
 *
 * Every record below is fictional and exists to exercise the UI while the
 * real opportunity catalog is being built. `isDemoData: true` is set on all
 * of them, and the UI must always surface that flag to the user — never
 * present this as verified, real opportunity data.
 *
 * Locations are set to real Capital Region, NY towns (Troy, Schenectady,
 * Albany, Guilderland, Saratoga Springs, Altamont) so the whole catalog
 * reads as locally relevant during development — but the organizations
 * themselves are fictional. When real opportunities are added, they must be
 * sourced from the organization's official page (see `officialUrl`/
 * `sourceUrl`) and go through the verification workflow before
 * `verificationStatus` can be anything other than NEEDS_VERIFICATION.
 */
export const demoOpportunities: Opportunity[] = [
  {
    id: "demo-1",
    title: "Summer Research Fellowship in Computational Biology",
    organization: "(Demo) Northfield Institute for Life Sciences",
    category: "RESEARCH",
    description:
      "A six-week mentored research fellowship pairing students with lab researchers on real computational biology projects, ending in a poster presentation.",
    eligibilityText:
      "Open to sophomores through seniors with an interest in biology, chemistry, or computer science. No prior lab experience required.",
    tags: ["biology", "computer science", "medicine", "research"],
    gradeMin: 10,
    gradeMax: 12,
    gpaRequirement: 3.3,
    location: "Troy, NY / Remote option available",
    remote: "HYBRID",
    cost: "FREE",
    costAmount: null,
    award: 500,
    deadline: "2027-03-15",
    deadlineNote: null,
    availabilityWindow: null,
    startDate: "2027-06-20",
    durationText: "6 weeks",
    experienceRequired: "NONE",
    requiredMaterials: ["Transcript", "Short essay", "1 teacher recommendation"],
    applicationProcessText:
      "Complete the online application with your transcript and a 300-word essay on a scientific question that interests you.",
    officialUrl: "https://example.org/demo-research-fellowship",
    sourceUrl: "https://example.org/demo-research-fellowship",
    verificationStatus: "NEEDS_VERIFICATION",
    lastVerifiedAt: null,
    regionTag: CAPITAL_REGION_TAG,
    isDemoData: true,
  },
  {
    id: "demo-2",
    title: "National Scholars Award for Academic Excellence",
    organization: "(Demo) Foundation for Future Leaders",
    category: "SCHOLARSHIP",
    description:
      "A merit-based scholarship supporting students who demonstrate strong academic performance and community involvement. Administered out of the Foundation's Albany office, open to applicants nationwide.",
    eligibilityText:
      "Open to juniors and seniors nationwide. GPA of 3.5 or higher required.",
    tags: ["leadership", "community service", "any major"],
    gradeMin: 11,
    gradeMax: 12,
    gpaRequirement: 3.5,
    location: "Albany, NY (national eligibility)",
    remote: "REMOTE",
    cost: "FREE",
    costAmount: null,
    award: 5000,
    deadline: "2027-01-31",
    deadlineNote: null,
    availabilityWindow: null,
    startDate: null,
    durationText: null,
    experienceRequired: "NONE",
    requiredMaterials: ["Transcript", "Personal statement", "2 recommendations"],
    applicationProcessText:
      "Submit transcript, a personal statement, and two letters of recommendation through the online portal.",
    officialUrl: "https://example.org/demo-scholars-award",
    sourceUrl: "https://example.org/demo-scholars-award",
    verificationStatus: "VERIFIED",
    lastVerifiedAt: "2026-08-01",
    regionTag: CAPITAL_REGION_TAG,
    isDemoData: true,
  },
  {
    id: "demo-3",
    title: "High School Software Engineering Internship",
    organization: "(Demo) Fieldstone Technologies",
    category: "INTERNSHIP",
    description:
      "A paid summer internship where students work alongside engineers at Fieldstone's Schenectady office on real product features, with weekly mentorship sessions.",
    eligibilityText:
      "Juniors and seniors with some coding experience (any language). Portfolio or GitHub link encouraged but not required.",
    tags: ["computer science", "engineering", "technology"],
    gradeMin: 11,
    gradeMax: 12,
    gpaRequirement: null,
    location: "Schenectady, NY / Remote",
    remote: "HYBRID",
    cost: "FREE",
    costAmount: null,
    award: 2000,
    deadline: "2027-02-10",
    deadlineNote: null,
    availabilityWindow: null,
    startDate: "2027-06-15",
    durationText: "8 weeks",
    experienceRequired: "SOME",
    requiredMaterials: ["Resume", "Short coding sample"],
    applicationProcessText:
      "Apply online with a resume and a short coding sample or project link.",
    officialUrl: "https://example.org/demo-swe-internship",
    sourceUrl: "https://example.org/demo-swe-internship",
    verificationStatus: "VERIFIED",
    lastVerifiedAt: "2026-07-18",
    regionTag: CAPITAL_REGION_TAG,
    isDemoData: true,
  },
  {
    id: "demo-4",
    title: "Youth Climate Action Fellowship",
    organization: "(Demo) Coalition for a Greener Tomorrow",
    category: "FELLOWSHIP",
    description:
      "A year-long fellowship for students to design and run a local environmental project with funding and mentor support, based out of Guilderland.",
    eligibilityText:
      "Open to all grade levels with an interest in environmental issues. No prior experience needed.",
    tags: ["environment", "sustainability", "community organizing"],
    gradeMin: 9,
    gradeMax: 12,
    gpaRequirement: null,
    location: "Guilderland, NY / Remote",
    remote: "HYBRID",
    cost: "FREE",
    costAmount: null,
    award: 1000,
    deadline: "2027-04-01",
    deadlineNote: null,
    availabilityWindow: null,
    startDate: "2027-05-01",
    durationText: "10 months",
    experienceRequired: "NONE",
    requiredMaterials: ["Project proposal (1 page)"],
    applicationProcessText:
      "Submit a one-page proposal describing a local environmental issue you want to address.",
    officialUrl: "https://example.org/demo-climate-fellowship",
    sourceUrl: "https://example.org/demo-climate-fellowship",
    verificationStatus: "NEEDS_VERIFICATION",
    lastVerifiedAt: null,
    regionTag: CAPITAL_REGION_TAG,
    isDemoData: true,
  },
  {
    id: "demo-5",
    title: "Regional Debate & Public Speaking Championship",
    organization: "(Demo) Lincoln Forum for Youth Debate",
    category: "COMPETITION",
    description:
      "An annual competition open to teams and individuals, held in Saratoga Springs with regional qualifiers leading to a national final.",
    eligibilityText: "Open to all high school students. Team or individual entries.",
    tags: ["debate", "public speaking", "law", "communications"],
    gradeMin: 9,
    gradeMax: 12,
    gpaRequirement: null,
    location: "Saratoga Springs, NY",
    remote: "IN_PERSON",
    cost: "PAID",
    costAmount: 45,
    award: 500,
    deadline: "2026-11-20",
    deadlineNote: null,
    availabilityWindow: null,
    startDate: "2027-01-18",
    durationText: "2 days",
    experienceRequired: "NONE",
    requiredMaterials: ["Registration form"],
    applicationProcessText: "Register your team or individual entry online before the deadline.",
    officialUrl: "https://example.org/demo-debate-championship",
    sourceUrl: "https://example.org/demo-debate-championship",
    verificationStatus: "VERIFIED",
    lastVerifiedAt: "2026-06-30",
    regionTag: CAPITAL_REGION_TAG,
    isDemoData: true,
  },
  {
    id: "demo-6",
    title: "Summer Pre-Med Discovery Program",
    organization: "(Demo) Alden University School of Medicine",
    category: "SUMMER_PROGRAM",
    description:
      "A two-week residential program introducing students to clinical shadowing, anatomy labs, and panels with medical students, hosted on Alden's Schenectady campus.",
    eligibilityText:
      "Sophomores through seniors interested in medicine. GPA 3.0+ recommended.",
    tags: ["medicine", "health", "biology"],
    gradeMin: 10,
    gradeMax: 12,
    gpaRequirement: 3.0,
    location: "Schenectady, NY",
    remote: "IN_PERSON",
    cost: "PAID",
    costAmount: 1200,
    award: null,
    deadline: "2027-03-01",
    deadlineNote: null,
    availabilityWindow: null,
    startDate: "2027-07-06",
    durationText: "2 weeks (residential)",
    experienceRequired: "NONE",
    requiredMaterials: ["Application form", "Transcript", "Parent consent form"],
    applicationProcessText:
      "Complete the application form with transcript and signed parent consent form. Need-based financial aid available.",
    officialUrl: "https://example.org/demo-premed-program",
    sourceUrl: "https://example.org/demo-premed-program",
    verificationStatus: "NEEDS_VERIFICATION",
    lastVerifiedAt: null,
    regionTag: CAPITAL_REGION_TAG,
    isDemoData: true,
  },
  {
    id: "demo-7",
    title: "Community Literacy Volunteer Corps",
    organization: "(Demo) Bright Pages Literacy Network",
    category: "VOLUNTEER",
    description:
      "An ongoing volunteer program where students tutor elementary schoolers in reading, either in person at the Altamont chapter or over video calls.",
    eligibilityText: "Open to all grade levels. Background check required for in-person roles.",
    tags: ["education", "community service", "tutoring"],
    gradeMin: 9,
    gradeMax: 12,
    gpaRequirement: null,
    location: "Altamont, NY / Remote",
    remote: "HYBRID",
    cost: "FREE",
    costAmount: null,
    award: null,
    deadline: "2027-05-01",
    deadlineNote: null,
    availabilityWindow: null,
    startDate: null,
    durationText: "Ongoing, min. 2 hrs/week",
    experienceRequired: "NONE",
    requiredMaterials: ["Volunteer application"],
    applicationProcessText: "Sign up online and complete a short volunteer orientation.",
    officialUrl: "https://example.org/demo-literacy-corps",
    sourceUrl: "https://example.org/demo-literacy-corps",
    verificationStatus: "VERIFIED",
    lastVerifiedAt: "2026-08-10",
    regionTag: CAPITAL_REGION_TAG,
    isDemoData: true,
  },
  {
    id: "demo-8",
    title: "Student Leadership Summit",
    organization: "(Demo) National Youth Leadership Council",
    category: "LEADERSHIP",
    description:
      "A three-day summit held in Albany bringing together student leaders for workshops on civic engagement, organizing, and public policy — steps from the state capitol.",
    eligibilityText: "Open to freshmen through seniors nominated by a teacher or self-nominated.",
    tags: ["leadership", "civics", "public policy"],
    gradeMin: 9,
    gradeMax: 12,
    gpaRequirement: null,
    location: "Albany, NY",
    remote: "IN_PERSON",
    cost: "PAID",
    costAmount: 350,
    award: null,
    deadline: "2027-02-20",
    deadlineNote: null,
    availabilityWindow: null,
    startDate: "2027-04-10",
    durationText: "3 days",
    experienceRequired: "NONE",
    requiredMaterials: ["Application essay"],
    applicationProcessText: "Submit a short essay on a civic issue you care about.",
    officialUrl: "https://example.org/demo-leadership-summit",
    sourceUrl: "https://example.org/demo-leadership-summit",
    verificationStatus: "EXPIRED",
    lastVerifiedAt: "2025-09-01",
    regionTag: CAPITAL_REGION_TAG,
    isDemoData: true,
  },
];
